<?php

namespace AppBundle\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTest()
    {
        return "test de pierre";
    }

    /**
     * @param $chauffeurSearch
     * 
     * @return Course[]
     */
    public function findByChauffeur($chauffeurSearch): array
    {
        $query = $this->getEntityManager()
                ->createQuery("
                SELECT 
                cou 
                FROM 
                AppBundle:Course cou JOIN cou.chauffeur cha
                WHERE 
                cha.nom LIKE :chauffeurSearch"
                        )
                ->setParameter('chauffeurSearch', '%'.$chauffeurSearch.'%');

        return $query->getResult();
    }

}
